version: "3.8"

services:
  spark-master:
    image: cmnemoi_spark:3.5.0
    container_name: spark-master
    ports:
      - 9090:8080
      - 7077:7077
      - 8888:8888
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
    volumes:
        - .:/cytech_sparks
  spark-worker-1:
    image: cmnemoi_spark:3.5.0
    container_name: spark-worker-1
    ports:
      - 9091:8080
      - 7000:7000
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-1
    volumes:
        - .:/cytech_sparks
  spark-worker-2:
    image: cmnemoi_spark:3.5.0
    container_name: spark-worker-2
    ports:
      - 9092:8080
      - 7001:7000
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-2
    volumes:
        - .:/cytech_sparks

